### ISSUE TITLE
Missing bootstrap-responsive.css file in resources/css

### ISSUE THREAD

**Issue by etabeta** [destructivecreator/ciunit-framework#2]
In your repository seems that You missed to add resources/css/bootstrap-responsive.css file requested by third_party/ciunit/views/index.php.
Can You check, please?
Thank You for your good job!!!

**Comment by destructivecreator** [comment]
bootstrap-responsive.css  is no longer part of the assets required by the web interface, I must have forgotten to remove it from views.

PS. Views are updated now

Great job reporting it!!
