### ISSUE TITLE
Unable to load views from class methods under test

### ISSUE THREAD

**Issue by jlocashio** [destructivecreator/ciunit-framework#4]
If I try to test a method that loads one of my app's views, CI tells me that it cannot load the requested file.

test call:
$notes = $this->get_instance()->site_misc->buildNotesTab('event', $this->filter['eventId']);

return from that method:
return $this->CI->load->view('forms/notes_form', array('notes' => @$notes, 'objectType' => $objectType, 'objectId' => $objectId), TRUE);

Any ideas as to why this is happening, and what I can do to resolve it?

**Comment by destructivecreator** [comment]
HI can you please provide the full test method and the error it generates?

Thanks

**Comment by jlocashio** [comment]
Test method:

``` php
public function testBuildNotesTab()
{
    $this->get_instance()->load->library('site_misc');    
    $notesTab = $this->get_instance()->site_misc->buildNotesTab('event', 179);
    $this->assertNotEmpty($notesTab);
}
```

The method under test is:

``` php
public function buildNotesTab($objectType, $objectId = NULL)
{
    if($this->CI->input->post('notes'))
    {
        $notes = $this->CI->input->post('notes');
    } else {
        $notes = json_encode($this->CI->notes_model->getNotes($objectType, $objectId));
    }

    return $this->CI->load->view('forms/notes_form', array('notes' => @$notes, 'objectType' => $objectType, 'objectId' => $objectId), TRUE);    
}
```

Where CI is a reference to the instance.

The error generated is a CI error page:

# An Error Was Encountered

Unable to load the requested file: forms/notes_form.php

I would point out that the method under test works fine from the app, so this doesn't appear to be a path issue on that side.

**Comment by destructivecreator** [comment]
Thanks for the update. It looks to me as CI tries to load it from within the CIUnit package rather than the main one. Try adding the following line in your test method or in a setup method in the test class. This will instruct codeigniter to look for view in the default folder "application/views"

``` php
public function testBuildNotesTab() {
    $this->get_instance()->load->add_package_path(APPPATH);
    ....
}
```

or

``` php
protected function setup() {
     $this->get_instance()->load->add_package_path(APPPATH);
}
```

If this fixes your issue I will revisit the code and merge the fix in master.

**Comment by jlocashio** [comment]
That seems to have worked. I'll add the call to my setup methods in the interim until you merge the fix.

Thanks for the help!

**Comment by ahtashamabbasse** [comment]
how to access in controller or model in test class?
