### ISSUE TITLE
Message: Undefined property: CI::$ciunit

### ISSUE THREAD

**Issue by kartikpatelp** [destructivecreator/ciunit-framework#5]
Hi,
I am Kartik, PHP Developer.
Thanks for you framework - it saves my lot of time.
I have configured it with my system. It is executed easily but it shows me one error, I am not able to solve it. So can you please help me

![error](https://cloud.githubusercontent.com/assets/6858943/5028201/4e2f5b72-6b5e-11e4-859c-378938e46b8e.png)

thanks in advance :)
(Kartik)

**Comment by destructivecreator** [comment]
Thanks for reporting, what version of CI are you running. Is that vanilla installation or it uses HVMC or similar ? Can you also provide a little bit more debugging around the MX/Loader.php e.g what is on line 168? 

Thanks

**Comment by kartikpatelp** [comment]
Thanks for your reply.
CI version = 2.1.0 and it is HMVC installation

This is error shows me whenever I do test for model classes, which are originally rest in ROOT/application/models foolder for my application.

In my MX/Loader.php on line 168 the following code has been written
![mx_loader](https://cloud.githubusercontent.com/assets/6858943/5041371/552522b2-6be6-11e4-819b-40620844b3dd.png)
Please help to solve this issue. It means lot of for me.

Thanks

**Comment by destructivecreator** [comment]
I suspected HMVC. Can you please give details on the CI setup you are running so that I can replicate the issue.
